apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web
spec:
  stripPrefix:
    prefixes:
      - /zy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kommander-traefik
    traefik.ingress.kubernetes.io/router.tls: "false"
    traefik.ingress.kubernetes.io/router.middlewares: zyproj-zy-app@kubernetescrd
  name: web-ingress
  namespace: zyproj
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 8081
        path: /zy
        pathType: Exact