apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

namespace: "zyproj"

namePrefix: "user01-"
nameSuffix: "-dev"

images:
  - name: "nginx"
    newName: "nginx"
    newTag: "1.28"


labels:
  - pairs:
      app.kubernetes.io/owner: "user01"
      app.kubernetes.io/name:
    includeSelectors: true
    includeTemplates: true

replicas:
  - name: web
    count: 3


